src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Media;

    /**
     * @ORM\Column(type="text")
     */
    private $Texte;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getMedia(): ?string
    {
        return $this->Media;
    }

    public function setMedia(string $Media): self
    {
        $this->Media = $Media;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): self
    {
        $this->Texte = $Texte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->Created_at;
    }

    public function setCreatedAt(\DateTimeInterface $Created_at): self
    {
        $this->Created_at = $Created_at;

        return $this;
    }
}

src/Entity/Sejours.php
<?php

namespace App\Entity;

use App\Repository\SejoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SejoursRepository::class)
 */
class Sejours
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Duree;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Prix;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\OneToMany(targetEntity=SejoursPictures::class, mappedBy="Sejours")
     */
    private $sejoursPictures;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $PrixTransport;

    public function __construct()
    {
        $this->sejoursPictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->Duree;
    }

    public function setDuree(string $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    public function __toString()
    {
        return $this->Titre;
    }


    /**
     * @return Collection|SejoursPictures[]
     */
    public function getSejoursPictures(): Collection
    {
        return $this->sejoursPictures;
    }

    public function addSejoursPicture(SejoursPictures $sejoursPicture): self
    {
        if (!$this->sejoursPictures->contains($sejoursPicture)) {
            $this->sejoursPictures[] = $sejoursPicture;
            $sejoursPicture->setSejours($this);
        }

        return $this;
    }

    public function removeSejoursPicture(SejoursPictures $sejoursPicture): self
    {
        if ($this->sejoursPictures->removeElement($sejoursPicture)) {
            // set the owning side to null (unless already changed)
            if ($sejoursPicture->getSejours() === $this) {
                $sejoursPicture->setSejours(null);
            }
        }

        return $this;
    }

    public function getPrixTransport(): ?string
    {
        return $this->PrixTransport;
    }

    public function setPrixTransport(string $PrixTransport): self
    {
        $this->PrixTransport = $PrixTransport;

        return $this;
    }
}

src/Entity/SejoursPictures.php
<?php

namespace App\Entity;

use App\Repository\SejoursPicturesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SejoursPicturesRepository::class)
 */
class SejoursPictures
{
    public function __toString()
    {
        return $this->name;
    }
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Picture;

    /**
     * @ORM\ManyToOne(targetEntity=Sejours::class, inversedBy="sejoursPictures")
     */
    private $Sejours;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(string $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getSejours(): ?Sejours
    {
        return $this->Sejours;
    }

    public function setSejours(?Sejours $Sejours): self
    {
        $this->Sejours = $Sejours;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Caroussel;
use App\Entity\Sejours;
use App\Entity\SejoursPictures;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        $caroussels = $this->getDoctrine()->getRepository(Caroussel::class)->findAll();
        $SejoursCaroussels = $this->getDoctrine()->getRepository(SejoursPictures::class)->findAll();
        $sejours = $this->getDoctrine()->getRepository(Sejours::class)->findOneBy([],['id' => 'DESC']);
        return $this->render('home/index.html.twig', [
            'sejours' => $sejours,
            'caroussels' => $caroussels,
            'SejoursCaroussels' => $SejoursCaroussels
        ]);
    }
    /**
     * @Route("/Projet", name="Projet")
     */
    public function projetEducatif(){
        return $this->render('home/ProjetEducatif.html.twig');
    }
}

templates/home/ProjetEducatif.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet Educatif
{% endblock %}
{% block javascripts %}
	{{parent()}}
	<script src="{{asset('js/app.js')}}"></script>
{% endblock %}
{% block body %}
    <img src="{{ asset('images/CssLogoCopie.png') }}" alt="logo" id="logoPe">
    <h1 id="CSS">Centrale <span>Sejours</span>  sports
    </h1>
    <h1>Projet Educatif</h1>
    <p>La structure Centrale Séjours Sports à pour but de favoriser la pratique d’activités sportives dont les valeurs s’inspirent de l’esprit et des méthodes des créateurs du sport moderne et la pédagogie active afin de permettre l’épanouissement de chacun.
        A cet effet on organise entre autres des séjours de vacances et des stages sportifs pour les enfants et adolescents</p>
<div class="col">
    <div>
        <h2>PUBLIC CONCERNÉ</h2>
        <p>Les activités de notre structure sont ouvertes à tous sans distinction sociale, politique, confessionnelle ou d’origine ethnique.</p>
    
    </div>
    <div>
        <h2>OBJECTIFS</h2>
        <p>Permettre aux enfants et adolescents de poursuivre le développement de leur personnalité d’une façon harmonieuse d’un point de vue social, moral, affectif, physique, culturel et spirituel, au cours d’un temps de vacances ludique et sportif.</p>    
    </div>
</div>


    <h2>1.Social, Moral et Affectif</h2>
    <ul>
        <li>Vivre en collectivité</li>
        <li>Trouver son identité tout en s’intégrant dans le groupe et son cadre
        </li>
        <li>Développer son autonomie</li>
        <li>Apprendre à accueillir et à vivre avec toute personne, venant de tout milieu</li>
        <li>Favoriser l’échange</li>
        <li>Vivre dans le respect mutuel des choses, des lieux, des idées et des hommes</li>
        <li>amener l’enfant à découvrir des pratiques variées favoriser acquisition de savoir technique</li>
        <li>favorisez la tolérance l’expression de la solidarité et la reconnaissance de la diversité</li>
        <li>favoriser l’ouverture des activités en incitant la mixité fille / garçon et les passerelles entre tranche d’age</li>

    </ul>

    <h2>2. Physique</h2>
    <div class="col2">
        <div>
            <p>Les pratiques sportives fédérales traditionnelles sur lesquelles nous nous appuyons sont choisies pour l’intérêt qu’elles suscitent auprès des enfants et des jeunes, ainsi que pour les perspectives éducatives qu’elles ouvrent. Nous les adaptons, les corrigeons, sans les dénaturer, pour les rendre formatrices afin de :

                Développer la motricité de chacun de façon adaptée à son âge et ses capacités
                Permettre l’expression corporelle, sportive…
                Aider à découvrir ses capacités et les développer
                Aider à développer son autonomie en acquérant des savoirs techniques</p>
        </div>
        <div>
            <img src="{{ asset('images/CssLogoCopie.png')}}" alt="logo" id="logo2PE">
        </div>
        
    </div>
    
    <h2>3. Culturel</h2>
    <ul>
        <li>Découvrir la culture sportive : éthique ; respect de l’adversaire, du coéquipier, de l’arbitrage et des règles ; sens de l’effort ; coopération</li>
        <li>Découvrir les autres cultures présentes dans le groupe ; échanger</li>
        <li>Sensibiliser à l’environnement naturel, culturel, traditionnel…</li>
    </ul>
    <h2>MOYENS :</h2>
    <h3>Équipements agréés et encadrement qualifié</h3>
    <p>Tant dans l’intérêt de la sécurité des enfants et des adolescents que pour mériter la confiance de leurs parents, nous voulons maintenir dans nos séjours un haut niveau d’exigence de qualité, c’est pourquoi notre structure offre tout particulièrement :</p>
    <ul>
        <li>Un encadrement qualifié (directeurs et animateurs souvent de surcroît diplômés en encadrement sportif brevet d ‘État Bafa Bepjeps et cff 2</li>
        <li>Des équipes d’encadrement compétentes, cohérentes, soudées autour de projets pédagogiques conformes à nos principes</li>
        <li>Des équipements agréés</li>
        <li>Des sites intéressants et offrant de nombreuses possibilités d’animations</li>
        <li>Des activités performantes et attrayantes</li>
        <li>Des animations en soirée de qualité</li>
    </ul>

    <p>Les directeurs et les animateurs des séjours collaborent habituellement pendant plusieurs années. Ceci nous permet de conserver des équipes stables et très engagées dans leur travail auprès des enfants.
        Ce projet éducatif est présenté aux équipes pédagogiques. Celles-ci ‘élaboration ensemble le projet pédagogique lors d’un week-end de préparation et de formation, sous l’autorité de l’équipe de direction.
        La structure s’engage à travailler avec toutes ses équipes dans la transparence et le sens des responsabilités, auprès des familles, des administrations, des autorités et des participants.
        Elle se donne les moyens d’informer, de prévenir tout risque ou dérapage et d’assurer la sécurité et l’intégrité des personnes dont elle a la charge.</p>

<p id="end">Centrale Séjours Sports Société Action Simplifié
    Siège Social : 86 BOULEVARD FÉLIX FAIRE – 93300O Aubervilliers Cedex
    Informations : 0665640203</p>


{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Centrale Sejours Sports
{% endblock %}
{% block javascripts %}
	{{parent()}}
	<script src="{{asset('js/app.js')}}"></script>
{% endblock %}
{% block body %}
	<section id="header">
		<div class="caroussel">
			<img src="{{ asset('images/thumbnail.jpg') }}" alt="" class="flyers">
		</div>
		<div class="head">
			<img class="" src="{{ asset('images/SLogo.png') }}" alt="" id="logoHome">
			<h1>Centrale<br>
				<span id="SejoursSpan">Sejours</span>
				Sports</h1>
		</div>
		<h1 id="head-text" class="animate__animated  animate__fadeInLeft">Leurs
			<span>Passion
			</span>
			<br>
			<span>Notre</span>
			Metier
		</h1>

	</div>
</section>

<section id="sejours">
	<div id="sejour">
		<div class="sejoursCard reveal-1">
			{% for SejoursCaroussel in SejoursCaroussels %}
				{% if SejoursCaroussel.sejours.id == sejours.id  %}
					<img src="{{ asset('images/'~ SejoursCaroussel.picture) }}" alt="" class="slide sejourscardimage">
					{% else %}
				{% endif %}
			{% endfor %}
			<button id="Prev">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewbox="0 0 16 16">
					<path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
				</svg>
			</button>
			<button id="Next">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewbox="0 0 16 16">
					<path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
				</svg>
			</button>
			<div class="sejourCardText1 reveal-2">
				<h3>{{ sejours.titre | raw}}
				</h3>
				<p class="ville">
					{{  sejours.ville }}
				</p>
			</div>
			<div class="sejourCardText2 reveal-3">
				<h3 class="sansTransport">
					{{ sejours.prix }}

				</h3>
				<p class="duree">
					{{ sejours.duree }}
					2021
				</p>
				<div id="button">
					<a href="{{ path('decouvrir_by_id', { id:sejours.id }) }}" class="other3">Decouvrir</a>
					{# <a href="{{ path('sejours') }}" class="other3">Decouvrir nos autre sejours</a> #}
				</div>

			</div>
		</div>
	</div>
</section>
<section>
	<div class="container-fluid video">
		<h1>Decouvrez La base du sejour</h1>
		<video src="{{ asset('video/file.mp4') }}" controls></video>
	</div>

</section>

<section id="Info" class="reveal-1">
	<h1 class="reveal-3">Qui somme nous
	</h1>
	<p class="reveal-3">La structure Centrale Séjours Sports à pour but de favoriser la pratique d’activités sportives dont les valeurs s’inspirent de l’esprit et des méthodes des créateurs du sport moderne et la pédagogie active afin de permettre l’épanouissement de chacun. A cet effet on organise entre autres des séjours de vacances et des stages sportifs pour les enfants et adolescents</p>
</section>
{# <section id="inscirption" class="reveal-3">
	<h1>Rejoignez-nous dès maintenant !</h1>
	<div id="inscriptionBlock">
		<div id="inscriptionText" class="reveal-3">
			<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur culpa cupiditate accusantium ea quia totam ratione alias laborum velit, nostrum deserunt rerum ducimus quo placeat tenetur numquam non iure quam.</p>
			<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur culpa cupiditate accusantium ea quia totam ratione alias laborum velit, nostrum deserunt rerum ducimus quo placeat tenetur numquam non iure quam.</p>
		</div>
		<div id="inscriptionButton" class="reveal-3">
			<a href="{{ path('inscription') }}" class="other2">Inscription</a>
		</div>
	</div>

</section> #}
<section id="Covid" class="reveal-1">
	<h1 class="reveal-3">Centrale Sejours Sports</h1>
	<div class="row">
		<div class="col-md-6">
			<p class="reveal-3">
				s'engage sur le protocole COVID-19 à respecter les gestes barrières durant le stage.<br>Mise à dispositions du gel hydroalcoolique ainsi que de masques.
				<br>
				Tous les matins, un animateur prendra la température de votre enfant avant de commencer les activités.<br>Une Chambre COVID sera mise en place.
			</p>
		</div>
		<div class="col-md-6">
			<img src="{{ asset('images/covid.jpg') }}" alt="" id="covidImage" class="rotating">
		</div>
	</div>
</section>
<section id="Partenaire" class="reveal-3">
	<h1>Nos Partenaires</h1>

	<div class="partenaires">
		<img src="{{ asset('images/rSport+.png') }}" alt="" class="partenaire">
		<img src="{{ asset('images/ifri.png') }}" alt="" class="partenaire">
		<img src="{{ asset('images/centrale.png') }}" alt="" class="partenaire">
	</div>


</section>{% endblock %}