src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogRepository::class)
 */
class Blog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Media;

    /**
     * @ORM\Column(type="text")
     */
    private $Texte;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getMedia(): ?string
    {
        return $this->Media;
    }

    public function setMedia(string $Media): self
    {
        $this->Media = $Media;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): self
    {
        $this->Texte = $Texte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->Created_at;
    }

    public function setCreatedAt(\DateTimeInterface $Created_at): self
    {
        $this->Created_at = $Created_at;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog")
     */
    public function index(): Response
    {
        $blog = $this->getDoctrine()->getRepository(Blog::class)->findAll();

        return $this->render('blog/index.html.twig', [
            'Blog' => $blog,
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur notre blog
{% endblock %}

{% block body %}
	<div class="blog">

        {% if Blog is empty  %}
            <div class="container mt-4">
            <h1>Blog en cours de construction</h1>
            <p>Retrouver prochainement les photos de nos sejours </p>
            
            </div>

            {% endif %}
		{% for blog in Blog %}

            <div class="blogArticle">
                <div class="blogHead">
                    <h1>{{ blog.titre }}</h1>
                    <small> {{ blog.createdAt | date }} </small>
                    <p> {{ blog.texte | raw }} </p>
                </div>
                <div class="blogIMG">
                    <img src="{{ asset('images/'~ blog.media) }}" alt="" class="">
                </div>
            </div>

        {% endfor %}


	</div>
{% endblock %}